### ISSUE TITLE
用orcspace是不是有问题

### ISSUE THREAD

**Issue by Agnon1573** [smileboywtu/MillionHeroAssistant#67]
使用orcspace怎么用不了？？？
/sdcard/screenshot.png: 1 file pulled. 12.7 MB/s (1463645 bytes in 0.110s)
screen width: 1080, screen height: 1920
Traceback (most recent call last):
name 'get_text_from_image' is not defined
  File "J:/MillionHeroAssistant-master (1)/MillionHeroAssistant-master/main.py", line 234, in main
按Enter键开始，按ESC键退出...    __inner_job()
  File "J:/MillionHeroAssistant-master (1)/MillionHeroAssistant-master/main.py", line 145, in __inner_job
    keywords = get_text_from_image(
NameError: name 'get_text_from_image' is not defined

**Comment by smileboywtu** [comment]
这个跟 ocr没有关系，这个是个bug 谢谢指出

**Comment by smileboywtu** [comment]
fix , please use latest

**Comment by Agnon1573** [comment]
OK，thank you!
