### ISSUE TITLE
运行报错 No module named 'ocr'

### ISSUE THREAD

**Issue by soxvpshubs** [smileboywtu/MillionHeroAssistant#71]
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from main import pre_process_question
  File "/home/MillionHeroAssistant/main.py", line 31, in <module>
    from core.ocr.baiduocr import get_text_from_image as bai_get_text
  File "/home/MillionHeroAssistant/core/ocr/baiduocr.py", line 9, in <module>
    from aip import AipOcr
  File "/usr/local/lib/python3.5/dist-packages/aip/__init__.py", line 6, in <module>
    from ocr import AipOcr
ImportError: No module named 'ocr'

```

Python 版本： Python 3.5.2

**Comment by soxvpshubs** [comment]
安装 baidu-aip `pip install baidu-aip` 解决了

**Comment by smileboywtu** [comment]
thxs  这是一个bug

**Comment by smileboywtu** [comment]
已经修复了
