### ISSUE TITLE
安装 requirements.txt 出错：OSError: [Errno 22] Invalid argument: '"c:\\program files\\python36\\Lib\\site-packages\\scikit_image-0.13.1-py3.6.egg-info\\installed-files.txt'

### ISSUE THREAD

**Issue by vimcaw** [smileboywtu/MillionHeroAssistant#79]
```
Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 922, in install
    with open(inst_files_path, 'w') as f:
OSError: [Errno 22] Invalid argument: '"c:\\program files\\python36\\Lib\\site-packages\\scikit_image-0.13.1-py3.6.egg-info\\installed-files.txt'
```

**Comment by vimcaw** [comment]
第二天再安装一次突然就好了
