### ISSUE TITLE
运行出错：KeyError: '10827486'

### ISSUE THREAD

**Issue by vimcaw** [smileboywtu/MillionHeroAssistant#80]
运行`python main.py`后报错：
```cmd
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from config import api_key, enable_chrome, use_monitor, image_compress_level, crop_areas
  File "C:\Users\vimcaw\Downloads\MillionHeroAssistant-master\config.py", line 23, in <module>
    app_id = config["10827486"]
KeyError: '10827486'
```

**Comment by smileboywtu** [comment]
你好 您这个应该是 自己填写的配置有问题，改错位置了  只能修改 config.yaml文件
